modLoader="javafml"
loaderVersion='(0,)'
license='WTFPL'

[[mods]]
modId='enchlevellangpatch'
version='${version}'
displayName='Enchantment Level Language Patch'
description='`enchantment.level.1000`, get off!'
authors='teddyxlandlee'
displayURL='https://modrinth.com/mod/enchlevel-langpatch'
issueTrackerURL='https://github.com/teddyxlandlee/enchlevel-langpatch/issues'
