modLoader="javafml"
loaderVersion='(0,)'
license='WTFPL'

[[mods]]
modId='enchlevellangpatch'
version='${version}'
displayName='Enchantment Level Language Patch'
description='`enchantment.level.1000`, get off!'
