modLoader="javafml"
loaderVersion='(0,)'
license='WTFPL'

[[mods]]
modId='enchlevellangpatch'
version='${version}'
displayName='Enchantment Level Language Patch'
description='Sharpness enchantment.level.255 => Sharpness 255/CCLV'
authors='teddyxlandlee'
displayURL='https://modrinth.com/mod/enchlevel-langpatch'
issueTrackerURL='https://github.com/teddyxlandlee/enchlevel-langpatch/issues'
