modLoader="javafml"
loaderVersion='(0,)'
license='LGPL-3.0'

[[mods]]
modId='enchlevellangpatch'
version='${file.jarVersion}'

#[[dependencies.enchlevellangpatch]]
#modId='fa2fomapper'
#mandatory=true
#versionRange='[1,2)'
#ordering='NONE'
#side='CLIENT'
