modLoader="javafml"
loaderVersion='(0,)'
license='WTFPL'

[[mods]]
namespace='xland.mcmod.enchlevel-langpatch'
modId='enchlevellangpatch'
version='${version}'
displayName='Enchantment Level Language Patch'
description='Sharpness enchantment.level.255 => Sharpness 255/CCLV'
modUrl='https://modrinth.com/mod/enchlevel-langpatch'
displayURL='https://modrinth.com/mod/enchlevel-langpatch'
issueTrackerURL='https://github.com/teddyxlandlee/enchlevel-langpatch/issues'
authors='teddyxlandlee'

[[mixins]]
config="ellp.mixins-forge.json"
